package com.yeadun.bigdata.platform.protocol;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

import java.util.ArrayList;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REQUEST = 1;</code>
     */
    REQUEST(0, 1),
    /**
     * <code>RESPONSE = 2;</code>
     */
    RESPONSE(1, 2),
    ;

    /**
     * <code>REQUEST = 1;</code>
     */
    public static final int REQUEST_VALUE = 1;
    /**
     * <code>RESPONSE = 2;</code>
     */
    public static final int RESPONSE_VALUE = 2;


    public final int getNumber() { return value; }

    public static MessageType valueOf(int value) {
      switch (value) {
        case 1: return REQUEST;
        case 2: return RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return MessageProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageType)
  }

  public interface messageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .MessageType type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>optional .MessageType type = 3;</code>
     */
    MessageProto.MessageType getType();

    /**
     * <code>optional bool finished = 4 [default = false];</code>
     */
    boolean hasFinished();
    /**
     * <code>optional bool finished = 4 [default = false];</code>
     */
    boolean getFinished();

    /**
     * <code>optional string input = 5;</code>
     */
    boolean hasInput();
    /**
     * <code>optional string input = 5;</code>
     */
    java.lang.String getInput();
    /**
     * <code>optional string input = 5;</code>
     */
    com.google.protobuf.ByteString
        getInputBytes();

    /**
     * <code>optional string output = 6;</code>
     */
    boolean hasOutput();
    /**
     * <code>optional string output = 6;</code>
     */
    java.lang.String getOutput();
    /**
     * <code>optional string output = 6;</code>
     */
    com.google.protobuf.ByteString
        getOutputBytes();

    /**
     * <code>repeated .DataPair messageBody = 7;</code>
     */
    java.util.ArrayList<MessageProto.DataPair> 
        getMessageBodyList();
    /**
     * <code>repeated .DataPair messageBody = 7;</code>
     */
    MessageProto.DataPair getMessageBody(int index);
    /**
     * <code>repeated .DataPair messageBody = 7;</code>
     */
    int getMessageBodyCount();
    /**
     * <code>repeated .DataPair messageBody = 7;</code>
     */
    java.util.ArrayList<? extends MessageProto.DataPairOrBuilder> 
        getMessageBodyOrBuilderList();
    /**
     * <code>repeated .DataPair messageBody = 7;</code>
     */
    MessageProto.DataPairOrBuilder getMessageBodyOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code message}
   */
  public static final class message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:message)
      messageOrBuilder {
    // Use message.newBuilder() to construct.
    private message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final message defaultInstance;
    public static message getDefaultInstance() {
      return defaultInstance;
    }

    public message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              MessageProto.MessageType value = MessageProto.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              finished_ = input.readBool();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              input_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              output_ = bs;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                messageBody_ = new java.util.ArrayList<MessageProto.DataPair>();
                mutable_bitField0_ |= 0x00000040;
              }
              messageBody_.add(input.readMessage(MessageProto.DataPair.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          messageBody_ = (ArrayList<DataPair>) java.util.Collections.unmodifiableList(messageBody_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProto.internal_static_message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProto.internal_static_message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageProto.message.class, MessageProto.message.Builder.class);
    }

    public static com.google.protobuf.Parser<message> PARSER =
        new com.google.protobuf.AbstractParser<message>() {
      public message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<message> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private MessageProto.MessageType type_;
    /**
     * <code>optional .MessageType type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .MessageType type = 3;</code>
     */
    public MessageProto.MessageType getType() {
      return type_;
    }

    public static final int FINISHED_FIELD_NUMBER = 4;
    private boolean finished_;
    /**
     * <code>optional bool finished = 4 [default = false];</code>
     */
    public boolean hasFinished() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool finished = 4 [default = false];</code>
     */
    public boolean getFinished() {
      return finished_;
    }

    public static final int INPUT_FIELD_NUMBER = 5;
    private java.lang.Object input_;
    /**
     * <code>optional string input = 5;</code>
     */
    public boolean hasInput() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string input = 5;</code>
     */
    public java.lang.String getInput() {
      java.lang.Object ref = input_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          input_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string input = 5;</code>
     */
    public com.google.protobuf.ByteString
        getInputBytes() {
      java.lang.Object ref = input_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        input_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OUTPUT_FIELD_NUMBER = 6;
    private java.lang.Object output_;
    /**
     * <code>optional string output = 6;</code>
     */
    public boolean hasOutput() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string output = 6;</code>
     */
    public java.lang.String getOutput() {
      java.lang.Object ref = output_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          output_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string output = 6;</code>
     */
    public com.google.protobuf.ByteString
        getOutputBytes() {
      java.lang.Object ref = output_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        output_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEBODY_FIELD_NUMBER = 7;
    private java.util.ArrayList<MessageProto.DataPair> messageBody_;
    /**
     * <code>repeated .DataPair messageBody = 7;</code>
     */
    public java.util.ArrayList<MessageProto.DataPair> getMessageBodyList() {
      return messageBody_;
    }
    /**
     * <code>repeated .DataPair messageBody = 7;</code>
     */
    public java.util.ArrayList<? extends MessageProto.DataPairOrBuilder> 
        getMessageBodyOrBuilderList() {
      return messageBody_;
    }
    /**
     * <code>repeated .DataPair messageBody = 7;</code>
     */
    public int getMessageBodyCount() {
      return messageBody_.size();
    }
    /**
     * <code>repeated .DataPair messageBody = 7;</code>
     */
    public MessageProto.DataPair getMessageBody(int index) {
      return messageBody_.get(index);
    }
    /**
     * <code>repeated .DataPair messageBody = 7;</code>
     */
    public MessageProto.DataPairOrBuilder getMessageBodyOrBuilder(
        int index) {
      return messageBody_.get(index);
    }

    private void initFields() {
      id_ = "";
      name_ = "Anonymous";
      type_ = MessageProto.MessageType.REQUEST;
      finished_ = false;
      input_ = "";
      output_ = "";
      messageBody_ = new ArrayList<DataPair>();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getMessageBodyCount(); i++) {
        if (!getMessageBody(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, finished_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getInputBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getOutputBytes());
      }
      for (int i = 0; i < messageBody_.size(); i++) {
        output.writeMessage(7, messageBody_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, finished_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getInputBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getOutputBytes());
      }
      for (int i = 0; i < messageBody_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, messageBody_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static MessageProto.message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProto.message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProto.message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProto.message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProto.message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MessageProto.message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static MessageProto.message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static MessageProto.message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static MessageProto.message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MessageProto.message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MessageProto.message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message)
        MessageProto.messageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProto.internal_static_message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProto.internal_static_message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageProto.message.class, MessageProto.message.Builder.class);
      }

      // Construct using MessageProto.message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessageBodyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "Anonymous";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = MessageProto.MessageType.REQUEST;
        bitField0_ = (bitField0_ & ~0x00000004);
        finished_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        input_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        output_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        if (messageBodyBuilder_ == null) {
          messageBody_ = new ArrayList<DataPair>();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          messageBodyBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProto.internal_static_message_descriptor;
      }

      public MessageProto.message getDefaultInstanceForType() {
        return MessageProto.message.getDefaultInstance();
      }

      public MessageProto.message build() {
        MessageProto.message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MessageProto.message buildPartial() {
        MessageProto.message result = new MessageProto.message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.finished_ = finished_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.input_ = input_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.output_ = output_;
        if (messageBodyBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
//            messageBody_ = java.util.Collections.unmodifiableList(messageBody_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = (ArrayList<DataPair>) messageBodyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageProto.message) {
          return mergeFrom((MessageProto.message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageProto.message other) {
        if (other == MessageProto.message.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasFinished()) {
          setFinished(other.getFinished());
        }
        if (other.hasInput()) {
          bitField0_ |= 0x00000010;
          input_ = other.input_;
          onChanged();
        }
        if (other.hasOutput()) {
          bitField0_ |= 0x00000020;
          output_ = other.output_;
          onChanged();
        }
        if (messageBodyBuilder_ == null) {
          if (!other.messageBody_.isEmpty()) {
            if (messageBody_.isEmpty()) {
              messageBody_ = other.messageBody_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureMessageBodyIsMutable();
              messageBody_.addAll(other.messageBody_);
            }
            onChanged();
          }
        } else {
          if (!other.messageBody_.isEmpty()) {
            if (messageBodyBuilder_.isEmpty()) {
              messageBodyBuilder_.dispose();
              messageBodyBuilder_ = null;
              messageBody_ = other.messageBody_;
              bitField0_ = (bitField0_ & ~0x00000040);
              messageBodyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMessageBodyFieldBuilder() : null;
            } else {
              messageBodyBuilder_.addAllMessages(other.messageBody_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMessageBodyCount(); i++) {
          if (!getMessageBody(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageProto.message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageProto.message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "Anonymous";
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private MessageProto.MessageType type_ = MessageProto.MessageType.REQUEST;
      /**
       * <code>optional .MessageType type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .MessageType type = 3;</code>
       */
      public MessageProto.MessageType getType() {
        return type_;
      }
      /**
       * <code>optional .MessageType type = 3;</code>
       */
      public Builder setType(MessageProto.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .MessageType type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = MessageProto.MessageType.REQUEST;
        onChanged();
        return this;
      }

      private boolean finished_ ;
      /**
       * <code>optional bool finished = 4 [default = false];</code>
       */
      public boolean hasFinished() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool finished = 4 [default = false];</code>
       */
      public boolean getFinished() {
        return finished_;
      }
      /**
       * <code>optional bool finished = 4 [default = false];</code>
       */
      public Builder setFinished(boolean value) {
        bitField0_ |= 0x00000008;
        finished_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool finished = 4 [default = false];</code>
       */
      public Builder clearFinished() {
        bitField0_ = (bitField0_ & ~0x00000008);
        finished_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object input_ = "";
      /**
       * <code>optional string input = 5;</code>
       */
      public boolean hasInput() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string input = 5;</code>
       */
      public java.lang.String getInput() {
        java.lang.Object ref = input_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            input_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string input = 5;</code>
       */
      public com.google.protobuf.ByteString
          getInputBytes() {
        java.lang.Object ref = input_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          input_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string input = 5;</code>
       */
      public Builder setInput(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        input_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string input = 5;</code>
       */
      public Builder clearInput() {
        bitField0_ = (bitField0_ & ~0x00000010);
        input_ = getDefaultInstance().getInput();
        onChanged();
        return this;
      }
      /**
       * <code>optional string input = 5;</code>
       */
      public Builder setInputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        input_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object output_ = "";
      /**
       * <code>optional string output = 6;</code>
       */
      public boolean hasOutput() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string output = 6;</code>
       */
      public java.lang.String getOutput() {
        java.lang.Object ref = output_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            output_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string output = 6;</code>
       */
      public com.google.protobuf.ByteString
          getOutputBytes() {
        java.lang.Object ref = output_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          output_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string output = 6;</code>
       */
      public Builder setOutput(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        output_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string output = 6;</code>
       */
      public Builder clearOutput() {
        bitField0_ = (bitField0_ & ~0x00000020);
        output_ = getDefaultInstance().getOutput();
        onChanged();
        return this;
      }
      /**
       * <code>optional string output = 6;</code>
       */
      public Builder setOutputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        output_ = value;
        onChanged();
        return this;
      }

      private java.util.ArrayList<MessageProto.DataPair> messageBody_ =
        new ArrayList<DataPair>();
      private void ensureMessageBodyIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          messageBody_ = new java.util.ArrayList<MessageProto.DataPair>(messageBody_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          MessageProto.DataPair, MessageProto.DataPair.Builder, MessageProto.DataPairOrBuilder> messageBodyBuilder_;

      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public java.util.ArrayList<MessageProto.DataPair> getMessageBodyList() {
        if (messageBodyBuilder_ == null) {
          return messageBody_;
        } else {
          return (ArrayList<DataPair>) messageBodyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public int getMessageBodyCount() {
        if (messageBodyBuilder_ == null) {
          return messageBody_.size();
        } else {
          return messageBodyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public MessageProto.DataPair getMessageBody(int index) {
        if (messageBodyBuilder_ == null) {
          return messageBody_.get(index);
        } else {
          return messageBodyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public Builder setMessageBody(
          int index, MessageProto.DataPair value) {
        if (messageBodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageBodyIsMutable();
          messageBody_.set(index, value);
          onChanged();
        } else {
          messageBodyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public Builder setMessageBody(
          int index, MessageProto.DataPair.Builder builderForValue) {
        if (messageBodyBuilder_ == null) {
          ensureMessageBodyIsMutable();
          messageBody_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageBodyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public Builder addMessageBody(MessageProto.DataPair value) {
        if (messageBodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageBodyIsMutable();
          messageBody_.add(value);
          onChanged();
        } else {
          messageBodyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public Builder addMessageBody(
          int index, MessageProto.DataPair value) {
        if (messageBodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageBodyIsMutable();
          messageBody_.add(index, value);
          onChanged();
        } else {
          messageBodyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public Builder addMessageBody(
          MessageProto.DataPair.Builder builderForValue) {
        if (messageBodyBuilder_ == null) {
          ensureMessageBodyIsMutable();
          messageBody_.add(builderForValue.build());
          onChanged();
        } else {
          messageBodyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public Builder addMessageBody(
          int index, MessageProto.DataPair.Builder builderForValue) {
        if (messageBodyBuilder_ == null) {
          ensureMessageBodyIsMutable();
          messageBody_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageBodyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public Builder addAllMessageBody(
          java.lang.Iterable<? extends MessageProto.DataPair> values) {
        if (messageBodyBuilder_ == null) {
          ensureMessageBodyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messageBody_);
          onChanged();
        } else {
          messageBodyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public Builder clearMessageBody() {
        if (messageBodyBuilder_ == null) {
          messageBody_ = new ArrayList<DataPair>();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          messageBodyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public Builder removeMessageBody(int index) {
        if (messageBodyBuilder_ == null) {
          ensureMessageBodyIsMutable();
          messageBody_.remove(index);
          onChanged();
        } else {
          messageBodyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public MessageProto.DataPair.Builder getMessageBodyBuilder(
          int index) {
        return getMessageBodyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public MessageProto.DataPairOrBuilder getMessageBodyOrBuilder(
          int index) {
        if (messageBodyBuilder_ == null) {
          return messageBody_.get(index);  } else {
          return messageBodyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public java.util.ArrayList<? extends MessageProto.DataPairOrBuilder> 
           getMessageBodyOrBuilderList() {
        if (messageBodyBuilder_ != null) {
          return (ArrayList<? extends DataPairOrBuilder>) messageBodyBuilder_.getMessageOrBuilderList();
        } else {
          return messageBody_;
        }
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public MessageProto.DataPair.Builder addMessageBodyBuilder() {
        return getMessageBodyFieldBuilder().addBuilder(
            MessageProto.DataPair.getDefaultInstance());
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public MessageProto.DataPair.Builder addMessageBodyBuilder(
          int index) {
        return getMessageBodyFieldBuilder().addBuilder(
            index, MessageProto.DataPair.getDefaultInstance());
      }
      /**
       * <code>repeated .DataPair messageBody = 7;</code>
       */
      public java.util.ArrayList<MessageProto.DataPair.Builder> 
           getMessageBodyBuilderList() {
        return (ArrayList<DataPair.Builder>) getMessageBodyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          MessageProto.DataPair, MessageProto.DataPair.Builder, MessageProto.DataPairOrBuilder> 
          getMessageBodyFieldBuilder() {
        if (messageBodyBuilder_ == null) {
          messageBodyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              MessageProto.DataPair, MessageProto.DataPair.Builder, MessageProto.DataPairOrBuilder>(
                  messageBody_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          messageBody_ = null;
        }
        return messageBodyBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:message)
    }

    static {
      defaultInstance = new message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:message)
  }

  public interface DataPairOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataPair)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional string val = 2;</code>
     */
    boolean hasVal();
    /**
     * <code>optional string val = 2;</code>
     */
    java.lang.String getVal();
    /**
     * <code>optional string val = 2;</code>
     */
    com.google.protobuf.ByteString
        getValBytes();

    /**
     * <code>optional string name = 3;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code DataPair}
   */
  public static final class DataPair extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DataPair)
      DataPairOrBuilder {
    // Use DataPair.newBuilder() to construct.
    private DataPair(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataPair(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataPair defaultInstance;
    public static DataPair getDefaultInstance() {
      return defaultInstance;
    }

    public DataPair getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataPair(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              val_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProto.internal_static_DataPair_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProto.internal_static_DataPair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageProto.DataPair.class, MessageProto.DataPair.Builder.class);
    }

    public static com.google.protobuf.Parser<DataPair> PARSER =
        new com.google.protobuf.AbstractParser<DataPair>() {
      public DataPair parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataPair(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataPair> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VAL_FIELD_NUMBER = 2;
    private java.lang.Object val_;
    /**
     * <code>optional string val = 2;</code>
     */
    public boolean hasVal() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string val = 2;</code>
     */
    public java.lang.String getVal() {
      java.lang.Object ref = val_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          val_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string val = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValBytes() {
      java.lang.Object ref = val_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        val_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
      val_ = "";
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static MessageProto.DataPair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProto.DataPair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProto.DataPair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProto.DataPair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProto.DataPair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MessageProto.DataPair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static MessageProto.DataPair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static MessageProto.DataPair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static MessageProto.DataPair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MessageProto.DataPair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MessageProto.DataPair prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataPair}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataPair)
        MessageProto.DataPairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProto.internal_static_DataPair_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProto.internal_static_DataPair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageProto.DataPair.class, MessageProto.DataPair.Builder.class);
      }

      // Construct using MessageProto.DataPair.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        val_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProto.internal_static_DataPair_descriptor;
      }

      public MessageProto.DataPair getDefaultInstanceForType() {
        return MessageProto.DataPair.getDefaultInstance();
      }

      public MessageProto.DataPair build() {
        MessageProto.DataPair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MessageProto.DataPair buildPartial() {
        MessageProto.DataPair result = new MessageProto.DataPair(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.val_ = val_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageProto.DataPair) {
          return mergeFrom((MessageProto.DataPair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageProto.DataPair other) {
        if (other == MessageProto.DataPair.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasVal()) {
          bitField0_ |= 0x00000002;
          val_ = other.val_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageProto.DataPair parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageProto.DataPair) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object val_ = "";
      /**
       * <code>optional string val = 2;</code>
       */
      public boolean hasVal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string val = 2;</code>
       */
      public java.lang.String getVal() {
        java.lang.Object ref = val_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            val_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string val = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValBytes() {
        java.lang.Object ref = val_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          val_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string val = 2;</code>
       */
      public Builder setVal(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        val_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string val = 2;</code>
       */
      public Builder clearVal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        val_ = getDefaultInstance().getVal();
        onChanged();
        return this;
      }
      /**
       * <code>optional string val = 2;</code>
       */
      public Builder setValBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        val_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DataPair)
    }

    static {
      defaultInstance = new DataPair(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DataPair)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataPair_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DataPair_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\"\242\001\n\007message\022\n\n\002id\030\001 \001(\t\022" +
      "\027\n\004name\030\002 \001(\t:\tAnonymous\022\032\n\004type\030\003 \001(\0162\014" +
      ".MessageType\022\027\n\010finished\030\004 \001(\010:\005false\022\r\n" +
      "\005input\030\005 \001(\t\022\016\n\006output\030\006 \001(\t\022\036\n\013messageB" +
      "ody\030\007 \003(\0132\t.DataPair\"2\n\010DataPair\022\013\n\003key\030" +
      "\001 \002(\t\022\013\n\003val\030\002 \001(\t\022\014\n\004name\030\003 \001(\t*(\n\013Mess" +
      "ageType\022\013\n\007REQUEST\020\001\022\014\n\010RESPONSE\020\002B\020B\014Me" +
      "ssageProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_message_descriptor,
        new java.lang.String[] { "Id", "Name", "Type", "Finished", "Input", "Output", "MessageBody", });
    internal_static_DataPair_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DataPair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DataPair_descriptor,
        new java.lang.String[] { "Key", "Val", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
