package com.yeadun.bigdata.platform.protocol;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

import java.util.ArrayList;

public final class ResponseProto {
  private ResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface responseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string input = 3;</code>
     */
    boolean hasInput();
    /**
     * <code>optional string input = 3;</code>
     */
    java.lang.String getInput();
    /**
     * <code>optional string input = 3;</code>
     */
    com.google.protobuf.ByteString
        getInputBytes();

    /**
     * <code>optional string output = 4;</code>
     */
    boolean hasOutput();
    /**
     * <code>optional string output = 4;</code>
     */
    java.lang.String getOutput();
    /**
     * <code>optional string output = 4;</code>
     */
    com.google.protobuf.ByteString
        getOutputBytes();

    /**
     * <code>repeated .DataPair messageBody = 5;</code>
     */
    java.util.ArrayList<DataPairProto.DataPair> 
        getMessageBodyList();
    /**
     * <code>repeated .DataPair messageBody = 5;</code>
     */
    DataPairProto.DataPair getMessageBody(int index);
    /**
     * <code>repeated .DataPair messageBody = 5;</code>
     */
    int getMessageBodyCount();
    /**
     * <code>repeated .DataPair messageBody = 5;</code>
     */
    java.util.ArrayList<? extends DataPairProto.DataPairOrBuilder> 
        getMessageBodyOrBuilderList();
    /**
     * <code>repeated .DataPair messageBody = 5;</code>
     */
    DataPairProto.DataPairOrBuilder getMessageBodyOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code response}
   */
  public static final class response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:response)
      responseOrBuilder {
    // Use response.newBuilder() to construct.
    private response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final response defaultInstance;
    public static response getDefaultInstance() {
      return defaultInstance;
    }

    public response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              input_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              output_ = bs;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                messageBody_ = new java.util.ArrayList<DataPairProto.DataPair>();
                mutable_bitField0_ |= 0x00000010;
              }
              messageBody_.add(input.readMessage(DataPairProto.DataPair.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          messageBody_ = (ArrayList<DataPairProto.DataPair>) messageBody_;
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ResponseProto.internal_static_response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ResponseProto.internal_static_response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResponseProto.response.class, ResponseProto.response.Builder.class);
    }

    public static com.google.protobuf.Parser<response> PARSER =
        new com.google.protobuf.AbstractParser<response>() {
      public response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INPUT_FIELD_NUMBER = 3;
    private java.lang.Object input_;
    /**
     * <code>optional string input = 3;</code>
     */
    public boolean hasInput() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string input = 3;</code>
     */
    public java.lang.String getInput() {
      java.lang.Object ref = input_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          input_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string input = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInputBytes() {
      java.lang.Object ref = input_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        input_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OUTPUT_FIELD_NUMBER = 4;
    private java.lang.Object output_;
    /**
     * <code>optional string output = 4;</code>
     */
    public boolean hasOutput() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string output = 4;</code>
     */
    public java.lang.String getOutput() {
      java.lang.Object ref = output_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          output_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string output = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOutputBytes() {
      java.lang.Object ref = output_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        output_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEBODY_FIELD_NUMBER = 5;
    private java.util.ArrayList<DataPairProto.DataPair> messageBody_;
    /**
     * <code>repeated .DataPair messageBody = 5;</code>
     */
    public java.util.ArrayList<DataPairProto.DataPair> getMessageBodyList() {
      return messageBody_;
    }
    /**
     * <code>repeated .DataPair messageBody = 5;</code>
     */
    public java.util.ArrayList<? extends DataPairProto.DataPairOrBuilder> 
        getMessageBodyOrBuilderList() {
      return messageBody_;
    }
    /**
     * <code>repeated .DataPair messageBody = 5;</code>
     */
    public int getMessageBodyCount() {
      return messageBody_.size();
    }
    /**
     * <code>repeated .DataPair messageBody = 5;</code>
     */
    public DataPairProto.DataPair getMessageBody(int index) {
      return messageBody_.get(index);
    }
    /**
     * <code>repeated .DataPair messageBody = 5;</code>
     */
    public DataPairProto.DataPairOrBuilder getMessageBodyOrBuilder(
        int index) {
      return messageBody_.get(index);
    }

    private void initFields() {
      id_ = "";
      name_ = "Anonymous";
      input_ = "";
      output_ = "";
      messageBody_ = new ArrayList<DataPairProto.DataPair>();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getInputBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getOutputBytes());
      }
      for (int i = 0; i < messageBody_.size(); i++) {
        output.writeMessage(5, messageBody_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getInputBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getOutputBytes());
      }
      for (int i = 0; i < messageBody_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, messageBody_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ResponseProto.response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseProto.response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseProto.response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseProto.response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseProto.response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ResponseProto.response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ResponseProto.response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ResponseProto.response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ResponseProto.response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ResponseProto.response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ResponseProto.response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:response)
        ResponseProto.responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ResponseProto.internal_static_response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ResponseProto.internal_static_response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResponseProto.response.class, ResponseProto.response.Builder.class);
      }

      // Construct using ResponseProto.response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessageBodyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "Anonymous";
        bitField0_ = (bitField0_ & ~0x00000002);
        input_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        output_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (messageBodyBuilder_ == null) {
          messageBody_ = new ArrayList<DataPairProto.DataPair>();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          messageBodyBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ResponseProto.internal_static_response_descriptor;
      }

      public ResponseProto.response getDefaultInstanceForType() {
        return ResponseProto.response.getDefaultInstance();
      }

      public ResponseProto.response build() {
        ResponseProto.response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ResponseProto.response buildPartial() {
        ResponseProto.response result = new ResponseProto.response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.input_ = input_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.output_ = output_;
        if (messageBodyBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            messageBody_ = (ArrayList<DataPairProto.DataPair>) messageBody_;
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = (ArrayList<DataPairProto.DataPair>) messageBodyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResponseProto.response) {
          return mergeFrom((ResponseProto.response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResponseProto.response other) {
        if (other == ResponseProto.response.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasInput()) {
          bitField0_ |= 0x00000004;
          input_ = other.input_;
          onChanged();
        }
        if (other.hasOutput()) {
          bitField0_ |= 0x00000008;
          output_ = other.output_;
          onChanged();
        }
        if (messageBodyBuilder_ == null) {
          if (!other.messageBody_.isEmpty()) {
            if (messageBody_.isEmpty()) {
              messageBody_ = other.messageBody_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureMessageBodyIsMutable();
              messageBody_.addAll(other.messageBody_);
            }
            onChanged();
          }
        } else {
          if (!other.messageBody_.isEmpty()) {
            if (messageBodyBuilder_.isEmpty()) {
              messageBodyBuilder_.dispose();
              messageBodyBuilder_ = null;
              messageBody_ = other.messageBody_;
              bitField0_ = (bitField0_ & ~0x00000010);
              messageBodyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMessageBodyFieldBuilder() : null;
            } else {
              messageBodyBuilder_.addAllMessages(other.messageBody_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResponseProto.response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResponseProto.response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "Anonymous";
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object input_ = "";
      /**
       * <code>optional string input = 3;</code>
       */
      public boolean hasInput() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string input = 3;</code>
       */
      public java.lang.String getInput() {
        java.lang.Object ref = input_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            input_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string input = 3;</code>
       */
      public com.google.protobuf.ByteString
          getInputBytes() {
        java.lang.Object ref = input_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          input_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string input = 3;</code>
       */
      public Builder setInput(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        input_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string input = 3;</code>
       */
      public Builder clearInput() {
        bitField0_ = (bitField0_ & ~0x00000004);
        input_ = getDefaultInstance().getInput();
        onChanged();
        return this;
      }
      /**
       * <code>optional string input = 3;</code>
       */
      public Builder setInputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        input_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object output_ = "";
      /**
       * <code>optional string output = 4;</code>
       */
      public boolean hasOutput() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string output = 4;</code>
       */
      public java.lang.String getOutput() {
        java.lang.Object ref = output_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            output_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string output = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOutputBytes() {
        java.lang.Object ref = output_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          output_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string output = 4;</code>
       */
      public Builder setOutput(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        output_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string output = 4;</code>
       */
      public Builder clearOutput() {
        bitField0_ = (bitField0_ & ~0x00000008);
        output_ = getDefaultInstance().getOutput();
        onChanged();
        return this;
      }
      /**
       * <code>optional string output = 4;</code>
       */
      public Builder setOutputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        output_ = value;
        onChanged();
        return this;
      }

      private java.util.ArrayList<DataPairProto.DataPair> messageBody_ =
        new ArrayList<DataPairProto.DataPair>();
      private void ensureMessageBodyIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          messageBody_ = new java.util.ArrayList<DataPairProto.DataPair>(messageBody_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          DataPairProto.DataPair, DataPairProto.DataPair.Builder, DataPairProto.DataPairOrBuilder> messageBodyBuilder_;

      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public java.util.ArrayList<DataPairProto.DataPair> getMessageBodyList() {
        if (messageBodyBuilder_ == null) {
          return (ArrayList<DataPairProto.DataPair>) messageBody_;
        } else {
          return (ArrayList<DataPairProto.DataPair>) messageBodyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public int getMessageBodyCount() {
        if (messageBodyBuilder_ == null) {
          return messageBody_.size();
        } else {
          return messageBodyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public DataPairProto.DataPair getMessageBody(int index) {
        if (messageBodyBuilder_ == null) {
          return messageBody_.get(index);
        } else {
          return messageBodyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public Builder setMessageBody(
          int index, DataPairProto.DataPair value) {
        if (messageBodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageBodyIsMutable();
          messageBody_.set(index, value);
          onChanged();
        } else {
          messageBodyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public Builder setMessageBody(
          int index, DataPairProto.DataPair.Builder builderForValue) {
        if (messageBodyBuilder_ == null) {
          ensureMessageBodyIsMutable();
          messageBody_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageBodyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public Builder addMessageBody(DataPairProto.DataPair value) {
        if (messageBodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageBodyIsMutable();
          messageBody_.add(value);
          onChanged();
        } else {
          messageBodyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public Builder addMessageBody(
          int index, DataPairProto.DataPair value) {
        if (messageBodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageBodyIsMutable();
          messageBody_.add(index, value);
          onChanged();
        } else {
          messageBodyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public Builder addMessageBody(
          DataPairProto.DataPair.Builder builderForValue) {
        if (messageBodyBuilder_ == null) {
          ensureMessageBodyIsMutable();
          messageBody_.add(builderForValue.build());
          onChanged();
        } else {
          messageBodyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public Builder addMessageBody(
          int index, DataPairProto.DataPair.Builder builderForValue) {
        if (messageBodyBuilder_ == null) {
          ensureMessageBodyIsMutable();
          messageBody_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageBodyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public Builder addAllMessageBody(
          java.lang.Iterable<? extends DataPairProto.DataPair> values) {
        if (messageBodyBuilder_ == null) {
          ensureMessageBodyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messageBody_);
          onChanged();
        } else {
          messageBodyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public Builder clearMessageBody() {
        if (messageBodyBuilder_ == null) {
          messageBody_ = new ArrayList<DataPairProto.DataPair>();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          messageBodyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public Builder removeMessageBody(int index) {
        if (messageBodyBuilder_ == null) {
          ensureMessageBodyIsMutable();
          messageBody_.remove(index);
          onChanged();
        } else {
          messageBodyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public DataPairProto.DataPair.Builder getMessageBodyBuilder(
          int index) {
        return getMessageBodyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public DataPairProto.DataPairOrBuilder getMessageBodyOrBuilder(
          int index) {
        if (messageBodyBuilder_ == null) {
          return messageBody_.get(index);  } else {
          return messageBodyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public java.util.ArrayList<? extends DataPairProto.DataPairOrBuilder> 
           getMessageBodyOrBuilderList() {
        if (messageBodyBuilder_ != null) {
          return (ArrayList<? extends DataPairProto.DataPairOrBuilder>) messageBodyBuilder_.getMessageOrBuilderList();
        } else {
          return (ArrayList<? extends DataPairProto.DataPairOrBuilder>) messageBody_;
        }
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public DataPairProto.DataPair.Builder addMessageBodyBuilder() {
        return getMessageBodyFieldBuilder().addBuilder(
            DataPairProto.DataPair.getDefaultInstance());
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public DataPairProto.DataPair.Builder addMessageBodyBuilder(
          int index) {
        return getMessageBodyFieldBuilder().addBuilder(
            index, DataPairProto.DataPair.getDefaultInstance());
      }
      /**
       * <code>repeated .DataPair messageBody = 5;</code>
       */
      public java.util.ArrayList<DataPairProto.DataPair.Builder> 
           getMessageBodyBuilderList() {
        return (ArrayList<DataPairProto.DataPair.Builder>) getMessageBodyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          DataPairProto.DataPair, DataPairProto.DataPair.Builder, DataPairProto.DataPairOrBuilder> 
          getMessageBodyFieldBuilder() {
        if (messageBodyBuilder_ == null) {
          messageBodyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              DataPairProto.DataPair, DataPairProto.DataPair.Builder, DataPairProto.DataPairOrBuilder>(
                  messageBody_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          messageBody_ = null;
        }
        return messageBodyBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:response)
    }

    static {
      defaultInstance = new response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Response.proto\032\016DataPair.proto\"n\n\010resp" +
      "onse\022\n\n\002id\030\001 \001(\t\022\027\n\004name\030\002 \001(\t:\tAnonymou" +
      "s\022\r\n\005input\030\003 \001(\t\022\016\n\006output\030\004 \001(\t\022\036\n\013mess" +
      "ageBody\030\005 \003(\0132\t.DataPairB\021B\rResponseProt" +
      "oH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          DataPairProto.getDescriptor()
        }, assigner);
    internal_static_response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_response_descriptor,
        new java.lang.String[] { "Id", "Name", "Input", "Output", "MessageBody", });
    DataPairProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
