package com.bigdata.platform.protocol;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

public final class ProtocolProto {
  private ProtocolProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code ProtocolType}
   */
  public enum ProtocolType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HDFS = 1;</code>
     */
    HDFS(0, 1),
    /**
     * <code>HBASE = 2;</code>
     */
    HBASE(1, 2),
    /**
     * <code>OTHER = 3;</code>
     */
    OTHER(2, 3),
    /**
     * <code>SPARK = 4;</code>
     */
    SPARK(3, 4),
    /**
     * <code>KAFKA = 5;</code>
     */
    KAFKA(4, 5),
    /**
     * <code>HIVE = 6;</code>
     */
    HIVE(5, 6),
    ;

    /**
     * <code>HDFS = 1;</code>
     */
    public static final int HDFS_VALUE = 1;
    /**
     * <code>HBASE = 2;</code>
     */
    public static final int HBASE_VALUE = 2;
    /**
     * <code>OTHER = 3;</code>
     */
    public static final int OTHER_VALUE = 3;
    /**
     * <code>SPARK = 4;</code>
     */
    public static final int SPARK_VALUE = 4;
    /**
     * <code>KAFKA = 5;</code>
     */
    public static final int KAFKA_VALUE = 5;
    /**
     * <code>HIVE = 6;</code>
     */
    public static final int HIVE_VALUE = 6;


    public final int getNumber() { return value; }

    public static ProtocolType valueOf(int value) {
      switch (value) {
        case 1: return HDFS;
        case 2: return HBASE;
        case 3: return OTHER;
        case 4: return SPARK;
        case 5: return KAFKA;
        case 6: return HIVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtocolType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProtocolType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtocolType>() {
            public ProtocolType findValueByNumber(int number) {
              return ProtocolType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ProtocolProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProtocolType[] VALUES = values();

    public static ProtocolType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ProtocolType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtocolType)
  }

  public interface protocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    String getName();
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional bool finished = 3 [default = false];</code>
     */
    boolean hasFinished();
    /**
     * <code>optional bool finished = 3 [default = false];</code>
     */
    boolean getFinished();

    /**
     * <code>optional .ProtocolType protocolType = 4 [default = OTHER];</code>
     */
    boolean hasProtocolType();
    /**
     * <code>optional .ProtocolType protocolType = 4 [default = OTHER];</code>
     */
    ProtocolType getProtocolType();

    /**
     * <code>optional .request request = 5;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .request request = 5;</code>
     */
    RequestProto.request getRequest();
    /**
     * <code>optional .request request = 5;</code>
     */
    RequestProto.requestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .response response = 6;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .response response = 6;</code>
     */
    ResponseProto.response getResponse();
    /**
     * <code>optional .response response = 6;</code>
     */
    ResponseProto.responseOrBuilder getResponseOrBuilder();

    /**
     * <code>optional string MetaInfo = 7;</code>
     */
    boolean hasMetaInfo();
    /**
     * <code>optional string MetaInfo = 7;</code>
     */
    String getMetaInfo();
    /**
     * <code>optional string MetaInfo = 7;</code>
     */
    com.google.protobuf.ByteString
        getMetaInfoBytes();
  }
  /**
   * Protobuf type {@code protocol}
   */
  public static final class protocol extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol)
      protocolOrBuilder {
    // Use protocol.newBuilder() to construct.
    private protocol(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private protocol(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final protocol defaultInstance;
    public static protocol getDefaultInstance() {
      return defaultInstance;
    }

    public protocol getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private protocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              finished_ = input.readBool();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              ProtocolType value = ProtocolType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                protocolType_ = value;
              }
              break;
            }
            case 42: {
              RequestProto.request.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(RequestProto.request.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              ResponseProto.response.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(ResponseProto.response.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              metaInfo_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocolProto.internal_static_protocol_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocolProto.internal_static_protocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.class, Builder.class);
    }

    public static com.google.protobuf.Parser<protocol> PARSER =
        new com.google.protobuf.AbstractParser<protocol>() {
      public protocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new protocol(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<protocol> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private Object name_;
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2 [default = "Anonymous"];</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FINISHED_FIELD_NUMBER = 3;
    private boolean finished_;
    /**
     * <code>optional bool finished = 3 [default = false];</code>
     */
    public boolean hasFinished() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool finished = 3 [default = false];</code>
     */
    public boolean getFinished() {
      return finished_;
    }

    public static final int PROTOCOLTYPE_FIELD_NUMBER = 4;
    private ProtocolType protocolType_;
    /**
     * <code>optional .ProtocolType protocolType = 4 [default = OTHER];</code>
     */
    public boolean hasProtocolType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .ProtocolType protocolType = 4 [default = OTHER];</code>
     */
    public ProtocolType getProtocolType() {
      return protocolType_;
    }

    public static final int REQUEST_FIELD_NUMBER = 5;
    private RequestProto.request request_;
    /**
     * <code>optional .request request = 5;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .request request = 5;</code>
     */
    public RequestProto.request getRequest() {
      return request_;
    }
    /**
     * <code>optional .request request = 5;</code>
     */
    public RequestProto.requestOrBuilder getRequestOrBuilder() {
      return request_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 6;
    private ResponseProto.response response_;
    /**
     * <code>optional .response response = 6;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .response response = 6;</code>
     */
    public ResponseProto.response getResponse() {
      return response_;
    }
    /**
     * <code>optional .response response = 6;</code>
     */
    public ResponseProto.responseOrBuilder getResponseOrBuilder() {
      return response_;
    }

    public static final int METAINFO_FIELD_NUMBER = 7;
    private Object metaInfo_;
    /**
     * <code>optional string MetaInfo = 7;</code>
     */
    public boolean hasMetaInfo() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string MetaInfo = 7;</code>
     */
    public String getMetaInfo() {
      Object ref = metaInfo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          metaInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string MetaInfo = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMetaInfoBytes() {
      Object ref = metaInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        metaInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      name_ = "Anonymous";
      finished_ = false;
      protocolType_ = ProtocolType.OTHER;
      request_ = RequestProto.request.getDefaultInstance();
      response_ = ResponseProto.response.getDefaultInstance();
      metaInfo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, finished_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, protocolType_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, request_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, response_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getMetaInfoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, finished_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, protocolType_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, request_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, response_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getMetaInfoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol)
        protocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtocolProto.internal_static_protocol_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtocolProto.internal_static_protocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.class, Builder.class);
      }

      // Construct using ProtocolProto.protocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
          getResponseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "Anonymous";
        bitField0_ = (bitField0_ & ~0x00000002);
        finished_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        protocolType_ = ProtocolType.OTHER;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (requestBuilder_ == null) {
          request_ = RequestProto.request.getDefaultInstance();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (responseBuilder_ == null) {
          response_ = ResponseProto.response.getDefaultInstance();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        metaInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtocolProto.internal_static_protocol_descriptor;
      }

      public protocol getDefaultInstanceForType() {
        return protocol.getDefaultInstance();
      }

      public protocol build() {
        protocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol buildPartial() {
        protocol result = new protocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.finished_ = finished_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.protocolType_ = protocolType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.metaInfo_ = metaInfo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol) {
          return mergeFrom((protocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol other) {
        if (other == protocol.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasFinished()) {
          setFinished(other.getFinished());
        }
        if (other.hasProtocolType()) {
          setProtocolType(other.getProtocolType());
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (other.hasMetaInfo()) {
          bitField0_ |= 0x00000040;
          metaInfo_ = other.metaInfo_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "Anonymous";
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = "Anonymous"];</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private boolean finished_ ;
      /**
       * <code>optional bool finished = 3 [default = false];</code>
       */
      public boolean hasFinished() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool finished = 3 [default = false];</code>
       */
      public boolean getFinished() {
        return finished_;
      }
      /**
       * <code>optional bool finished = 3 [default = false];</code>
       */
      public Builder setFinished(boolean value) {
        bitField0_ |= 0x00000004;
        finished_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool finished = 3 [default = false];</code>
       */
      public Builder clearFinished() {
        bitField0_ = (bitField0_ & ~0x00000004);
        finished_ = false;
        onChanged();
        return this;
      }

      private ProtocolType protocolType_ = ProtocolType.OTHER;
      /**
       * <code>optional .ProtocolType protocolType = 4 [default = OTHER];</code>
       */
      public boolean hasProtocolType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .ProtocolType protocolType = 4 [default = OTHER];</code>
       */
      public ProtocolType getProtocolType() {
        return protocolType_;
      }
      /**
       * <code>optional .ProtocolType protocolType = 4 [default = OTHER];</code>
       */
      public Builder setProtocolType(ProtocolType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        protocolType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ProtocolType protocolType = 4 [default = OTHER];</code>
       */
      public Builder clearProtocolType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        protocolType_ = ProtocolType.OTHER;
        onChanged();
        return this;
      }

      private RequestProto.request request_ = RequestProto.request.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          RequestProto.request, RequestProto.request.Builder, RequestProto.requestOrBuilder> requestBuilder_;
      /**
       * <code>optional .request request = 5;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .request request = 5;</code>
       */
      public RequestProto.request getRequest() {
        if (requestBuilder_ == null) {
          return request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .request request = 5;</code>
       */
      public Builder setRequest(RequestProto.request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .request request = 5;</code>
       */
      public Builder setRequest(
          RequestProto.request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .request request = 5;</code>
       */
      public Builder mergeRequest(RequestProto.request value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              request_ != RequestProto.request.getDefaultInstance()) {
            request_ =
              RequestProto.request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .request request = 5;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = RequestProto.request.getDefaultInstance();
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .request request = 5;</code>
       */
      public RequestProto.request.Builder getRequestBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .request request = 5;</code>
       */
      public RequestProto.requestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_;
        }
      }
      /**
       * <code>optional .request request = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          RequestProto.request, RequestProto.request.Builder, RequestProto.requestOrBuilder>
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              RequestProto.request, RequestProto.request.Builder, RequestProto.requestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private ResponseProto.response response_ = ResponseProto.response.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ResponseProto.response, ResponseProto.response.Builder, ResponseProto.responseOrBuilder> responseBuilder_;
      /**
       * <code>optional .response response = 6;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .response response = 6;</code>
       */
      public ResponseProto.response getResponse() {
        if (responseBuilder_ == null) {
          return response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .response response = 6;</code>
       */
      public Builder setResponse(ResponseProto.response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .response response = 6;</code>
       */
      public Builder setResponse(
          ResponseProto.response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .response response = 6;</code>
       */
      public Builder mergeResponse(ResponseProto.response value) {
        if (responseBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              response_ != ResponseProto.response.getDefaultInstance()) {
            response_ =
              ResponseProto.response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .response response = 6;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = ResponseProto.response.getDefaultInstance();
          onChanged();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .response response = 6;</code>
       */
      public ResponseProto.response.Builder getResponseBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .response response = 6;</code>
       */
      public ResponseProto.responseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_;
        }
      }
      /**
       * <code>optional .response response = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ResponseProto.response, ResponseProto.response.Builder, ResponseProto.responseOrBuilder>
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ResponseProto.response, ResponseProto.response.Builder, ResponseProto.responseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private Object metaInfo_ = "";
      /**
       * <code>optional string MetaInfo = 7;</code>
       */
      public boolean hasMetaInfo() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string MetaInfo = 7;</code>
       */
      public String getMetaInfo() {
        Object ref = metaInfo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            metaInfo_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string MetaInfo = 7;</code>
       */
      public com.google.protobuf.ByteString
          getMetaInfoBytes() {
        Object ref = metaInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          metaInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string MetaInfo = 7;</code>
       */
      public Builder setMetaInfo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        metaInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string MetaInfo = 7;</code>
       */
      public Builder clearMetaInfo() {
        bitField0_ = (bitField0_ & ~0x00000040);
        metaInfo_ = getDefaultInstance().getMetaInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string MetaInfo = 7;</code>
       */
      public Builder setMetaInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        metaInfo_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol)
    }

    static {
      defaultInstance = new protocol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Protocol.proto\032\rRequest.proto\032\016Respons" +
      "e.proto\"\276\001\n\010protocol\022\n\n\002id\030\001 \001(\t\022\027\n\004name" +
      "\030\002 \001(\t:\tAnonymous\022\027\n\010finished\030\003 \001(\010:\005fal" +
      "se\022*\n\014protocolType\030\004 \001(\0162\r.ProtocolType:" +
      "\005OTHER\022\031\n\007request\030\005 \001(\0132\010.request\022\033\n\010res" +
      "ponse\030\006 \001(\0132\t.response\022\020\n\010MetaInfo\030\007 \001(\t" +
      "*N\n\014ProtocolType\022\010\n\004HDFS\020\001\022\t\n\005HBASE\020\002\022\t\n" +
      "\005OTHER\020\003\022\t\n\005SPARK\020\004\022\t\n\005KAFKA\020\005\022\010\n\004HIVE\020\006" +
      "B\021B\rProtocolProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          RequestProto.getDescriptor(),
          ResponseProto.getDescriptor()
        }, assigner);
    internal_static_protocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_descriptor,
        new String[] { "Id", "Name", "Finished", "ProtocolType", "Request", "Response", "MetaInfo", });
    RequestProto.getDescriptor();
    ResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
